# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true
sudo: false
cache: packages
os:
 - linux
r:
 - devel
before_deploy: Rscript -e 'remotes::install_cran("pkgdown"); covr::codecov();'
git:
   depth: 9999999
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
